# Generated by Django 6.0.4 on 2026-04-22 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('source_platform', models.CharField(choices=[('SEEK', 'Seek'), ('LINKEDIN', 'LinkedIn'), ('INDEED', 'Indeed'), ('MANUAL', 'Manual'), ('OTHER', 'Other')], default='MANUAL', max_length=20)),
                ('job_url', models.URLField(blank=True)),
                ('date_posted', models.DateField(blank=True, null=True)),
                ('date_applied', models.DateField(blank=True, null=True)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='AUD', max_length=10)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('FOUND', 'Found'), ('APPLIED', 'Applied'), ('INTERVIEWING', 'Interviewing'), ('OFFER', 'Offer'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='FOUND', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
