# Generated by Django 6.0.4 on 2026-04-23 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='source_details',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='source_platform',
            field=models.CharField(choices=[('SEEK', 'Seek'), ('LINKEDIN', 'LinkedIn'), ('INDEED', 'Indeed'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
