# Generated by Django 6.0.4 on 2026-04-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_applicationcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationcontact',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
