# Generated by Django 6.0.4 on 2026-05-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_alter_jobapplication_source_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='source_platform',
            field=models.CharField(blank=True, choices=[('SEEK', 'Seek'), ('LINKEDIN', 'LinkedIn'), ('INDEED', 'Indeed'), ('OTHER', 'Other'), ('', 'Not specified')], default='', max_length=20),
        ),
    ]
