# Generated by Django 6.0.4 on 2026-05-04 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_remove_jobapplication_notes_applicationnote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationnote',
            name='is_active',
        ),
    ]
