# Generated by Django 6.0.4 on 2026-05-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_alter_jobapplication_source_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='interest_level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
