# Generated by Django 6.0.4 on 2026-05-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_jobapplication_interest_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='job_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
