# Generated by Django 6.0.4 on 2026-05-04 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_remove_applicationnote_is_active'),
        ('applications', '0009_alter_jobapplication_job_url'),
    ]

    operations = [
    ]
