# Generated by Django 5.1 on 2026-05-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_merge_20260504_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationcontact',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='applicationnote',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
