# Generated by Django 6.0.4 on 2026-05-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_remove_jobapplication_notes_applicationnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
