# Generated by Codex on 2026-05-11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0011_jobapplication_archived_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("INTERVIEW", "Interview"),
                            ("CALL", "Call"),
                            ("DEADLINE", "Deadline"),
                            ("OTHER", "Other"),
                        ],
                        default="INTERVIEW",
                        max_length=20,
                    ),
                ),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("meeting_link", models.URLField(blank=True, max_length=2000)),
                ("contact_name", models.CharField(blank=True, max_length=255)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=50)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job_application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="applications.jobapplication",
                    ),
                ),
            ],
            options={
                "ordering": ["starts_at"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("TAILOR_RESUME", "Tailor resume"),
                            ("COVER_LETTER", "Prepare cover letter"),
                            ("SUBMIT_APPLICATION", "Submit application"),
                            ("FOLLOW_UP", "Follow up"),
                            ("INTERVIEW_PREP", "Prepare for interview"),
                            ("INTERVIEW_FOLLOW_UP", "Interview follow-up"),
                            ("REJECTION_FEEDBACK", "Ask for feedback"),
                            ("OFFER_REVIEW", "Review offer"),
                            ("CUSTOM", "Custom"),
                        ],
                        default="CUSTOM",
                        max_length=40,
                    ),
                ),
                (
                    "source_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FOUND", "Found"),
                            ("APPLIED", "Applied"),
                            ("INTERVIEWING", "Interviewing"),
                            ("OFFER", "Offer"),
                            ("REJECTED", "Rejected"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        max_length=20,
                    ),
                ),
                ("auto_created", models.BooleanField(default=False)),
                ("is_required", models.BooleanField(default=True)),
                (
                    "triggers_status_change_to",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FOUND", "Found"),
                            ("APPLIED", "Applied"),
                            ("INTERVIEWING", "Interviewing"),
                            ("OFFER", "Offer"),
                            ("REJECTED", "Rejected"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job_application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="applications.jobapplication",
                    ),
                ),
            ],
            options={
                "ordering": ["completed_at", "due_at", "created_at"],
            },
        ),
    ]
