# Generated by Codex on 2026-05-11

from datetime import timedelta

from django.db import migrations
from django.utils import timezone


FOUND_TASKS = [
    {
        "task_type": "TAILOR_RESUME",
        "title": "Tailor resume for this role",
        "description": "Adjust your resume so the most relevant experience and skills match this vacancy.",
        "source_status": "FOUND",
        "is_required": True,
        "triggers_status_change_to": "",
    },
    {
        "task_type": "COVER_LETTER",
        "title": "Prepare cover letter",
        "description": "Write a short cover letter if the vacancy asks for one or if it would strengthen your application.",
        "source_status": "FOUND",
        "is_required": False,
        "triggers_status_change_to": "",
    },
    {
        "task_type": "SUBMIT_APPLICATION",
        "title": "Submit application",
        "description": "Send the application. Completing this task moves the card to Applied.",
        "source_status": "FOUND",
        "is_required": True,
        "triggers_status_change_to": "APPLIED",
    },
]


STATUS_TASKS = {
    "APPLIED": [
        {
            "task_type": "FOLLOW_UP",
            "title": "Follow up with the company",
            "description": "If you have not heard back, find a relevant HR/contact person and let them know you applied.",
            "source_status": "APPLIED",
            "is_required": False,
            "due_at": lambda: timezone.now() + timedelta(days=7),
        },
    ],
    "INTERVIEWING": [
        {
            "task_type": "INTERVIEW_PREP",
            "title": "Prepare for the interview",
            "description": "Review the role, prepare examples, questions, and logistics before the interview.",
            "source_status": "INTERVIEWING",
            "is_required": False,
        },
    ],
    "REJECTED": [
        {
            "task_type": "REJECTION_FEEDBACK",
            "title": "Thank them and ask for feedback",
            "description": "Send a polite thank-you note and ask whether they can share feedback for future applications.",
            "source_status": "REJECTED",
            "is_required": False,
        },
    ],
    "OFFER": [
        {
            "task_type": "OFFER_REVIEW",
            "title": "Review offer details",
            "description": "Check salary, benefits, start date, response deadline, and questions before accepting.",
            "source_status": "OFFER",
            "is_required": True,
        },
    ],
}


def create_auto_task(ApplicationTask, application, defaults):
    if ApplicationTask.objects.filter(
        job_application=application,
        task_type=defaults["task_type"],
        auto_created=True,
    ).exists():
        return

    task_defaults = {
        "job_application": application,
        "auto_created": True,
        "triggers_status_change_to": "",
        "due_at": None,
        **defaults,
    }

    if callable(task_defaults["due_at"]):
        task_defaults["due_at"] = task_defaults["due_at"]()

    ApplicationTask.objects.create(**task_defaults)


def backfill_application_tasks(apps, schema_editor):
    JobApplication = apps.get_model("applications", "JobApplication")
    ApplicationTask = apps.get_model("applications", "ApplicationTask")

    applications = JobApplication.objects.filter(is_active=True, is_archived=False)

    for application in applications.iterator():
        if application.status == "FOUND":
            for task in FOUND_TASKS:
                create_auto_task(ApplicationTask, application, task)

        for task in STATUS_TASKS.get(application.status, []):
            create_auto_task(ApplicationTask, application, task)


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0012_applicationevent_applicationtask"),
    ]

    operations = [
        migrations.RunPython(backfill_application_tasks, migrations.RunPython.noop),
    ]
