# Generated by Codex on 2026-05-11

from django.db import migrations, models
from django.db.models import Count


def first_present(tasks, field_name):
    for task in tasks:
        value = getattr(task, field_name)
        if value:
            return value

    return getattr(tasks[0], field_name)


def dedupe_auto_tasks(apps, schema_editor):
    ApplicationTask = apps.get_model("applications", "ApplicationTask")

    duplicate_groups = (
        ApplicationTask.objects.filter(auto_created=True)
        .values("job_application_id", "task_type")
        .annotate(task_count=Count("id"))
        .filter(task_count__gt=1)
    )

    for group in duplicate_groups:
        tasks = list(
            ApplicationTask.objects.filter(
                auto_created=True,
                job_application_id=group["job_application_id"],
                task_type=group["task_type"],
            ).order_by("id")
        )

        completed_tasks = [task for task in tasks if task.completed_at]

        if completed_tasks:
            keep_task = max(
                completed_tasks,
                key=lambda task: (task.completed_at, task.id),
            )
        else:
            keep_task = tasks[0]

        completed_at_values = [task.completed_at for task in tasks if task.completed_at]
        due_at_values = [task.due_at for task in tasks if task.due_at]
        other_task_ids = [task.id for task in tasks if task.id != keep_task.id]

        keep_task.title = first_present(tasks, "title")
        keep_task.description = first_present(tasks, "description")
        keep_task.source_status = first_present(tasks, "source_status")
        keep_task.triggers_status_change_to = first_present(
            tasks,
            "triggers_status_change_to",
        )
        keep_task.is_required = any(task.is_required for task in tasks)

        if completed_at_values:
            keep_task.completed_at = max(completed_at_values)

        if due_at_values:
            keep_task.due_at = min(due_at_values)

        keep_task.save(
            update_fields=[
                "title",
                "description",
                "source_status",
                "triggers_status_change_to",
                "is_required",
                "completed_at",
                "due_at",
                "updated_at",
            ]
        )

        ApplicationTask.objects.filter(id__in=other_task_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0013_backfill_application_tasks"),
    ]

    operations = [
        migrations.RunPython(dedupe_auto_tasks, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="applicationtask",
            constraint=models.UniqueConstraint(
                condition=models.Q(("auto_created", True)),
                fields=("job_application", "task_type"),
                name="unique_auto_task_per_application_type",
            ),
        ),
    ]
