# Generated by Codex on 2026-05-12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0014_dedupe_application_tasks"),
    ]

    operations = []
