# Generated by Django 6.0.4 on 2026-05-12 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_alter_applicationcontact_id_alter_applicationnote_id_and_more'),
        ('applications', '0015_spread_duplicate_task_due_times'),
    ]

    operations = [
    ]
