# Generated by Django 6.0.4 on 2026-05-17 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message_type', models.CharField(choices=[('BUG', 'Bug report'), ('QUESTION', 'Question'), ('ACCOUNT_RECOVERY', 'Account recovery'), ('SUGGESTION', 'Suggestion'), ('OTHER', 'Other')], default='QUESTION', max_length=30)),
                ('related_page', models.CharField(choices=[('DASHBOARD', 'Dashboard'), ('JOB_APPLICATION', 'Job Application'), ('TASKS_EVENTS', 'Tasks and Events'), ('PROFILE', 'Profile'), ('LOGIN_SIGNUP', 'Login / Sign up'), ('ACCOUNT_RECOVERY', 'Account recovery'), ('OTHER', 'Other')], default='OTHER', max_length=40)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('consent_given', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
