# Generated by Django 6.0.4 on 2026-05-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmessage',
            name='page_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
