# Generated by Django 6.0.4 on 2026-04-23 05:06

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('woman', 'Woman'), ('man', 'Man'), ('non_binary', 'Non-binary'), ('prefer_not_to_say', 'Prefer not to say'), ('self_describe', 'Self-describe')], max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender_self_described',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
