# Generated by Django 6.0.4 on 2026-05-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='auto_archive_days',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
