# Generated by Django 6.0.4 on 2026-05-12 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_id'),
        ('accounts', '0004_profile_auto_archive_days'),
    ]

    operations = [
    ]
