# Generated by Codex on 2026-05-18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "resource_type",
                    models.CharField(
                        choices=[("ARTICLE", "Article"), ("CHATGPT", "ChatGPT answer")],
                        default="ARTICLE",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("source_name", models.CharField(blank=True, max_length=255)),
                ("author", models.CharField(blank=True, max_length=255)),
                ("published_at", models.DateField(blank=True, null=True)),
                ("url", models.URLField(blank=True, max_length=2000)),
                ("question", models.TextField(blank=True)),
                ("answer", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
